MinAlertLevel = suggestion

Packages = Google, alex, proselint

[*.{md,txt,org}]
BasedOnStyles = Vale, Alex, 

# Turn off annoying categories
Vale.Terms = YES
Vale.Avoid = YES
Vale.Passive = YES
Vale.Weasel = YES
