;; -*- mode: eask; lexical-binding: t -*-

(package "dot-emacs"
         "0.2.0"
         "that1guycolin's dot-Emacs")

(website-url "https://github.com/that1guycolin/dot-emacs.git")
(keywords "emacs" "config" "elisp" "emacs-lisp")

(package-file "~/.emacs.d/init.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)
(source 'jcs-elpa)

(depends-on "emacs" "30.2")

(development
 (depends-on "elsa" "0.1.0")
 (depends-on "ellsp" "0.1.0"))
