;;; 03-visual-settings.el --- Core UI configuration -*- lexical-binding: t; -*-

;;; Packages included:

;;; Packages included:
;; editorconfig, ef-themes, folding-mode, minions, modus-themes, nerd-icons,
;; nerd-icons-corfu, tab-line-nerd-icons, visual-fill-column, which-key

;;; Commentary:
;; Core UI elements that provide visual feedback and interaction.

;;; Code:
;; Start fullscreen.
(add-to-list 'default-frame-alist '(fullscreen . maximized))

;; =======  THEMES  =======
;; `modus-themes' (Collection of readable Emacs' themes)
;; `ef-themes' (Additional & enhanced Emacs' themes)
;; ========================
(use-package modus-themes
  :demand t
  :functions
  modus-themes-include-derivatives-mode modus-themes-load-random-dark
  modus-themes-select-dark modus-themes-load-random modus-themes-rotate)

(use-package ef-themes
  :demand t
  :preface
  (declare-function user/function-after-emacsclient-frame
		    "01-bootstrap-core.el")
  (defvar user/ef-themes-startup-messages nil)

  (defun user/flush-startup-messages ()
    "Print messages held in `user/ef-themes-startup-messages'.
Messages are printed in the order in which they were received"
    (dolist (msg (nreverse user/ef-themes-startup-messages))
      (message "%s" msg))
    (setq user/ef-themes-startup-messages nil))

  (defun user/message-after-startup (msg)
    "Wait until after init to print MSG.
If Emacs has already started, print MSG right away."
    (if after-init-time
	(message "%s" msg)
      (push msg user/ef-themes-startup-messages)
      (add-hook 'emacs-startup-hook #'user/flush-startup-messages)))

  (defun user/delay-messages-around (orig-fun &rest args)
    "Delay the messages generated by ORIG-FUN until after startup.
Designed to be used with `advice-add', you can pass ARGS to the ORIG-FN
as well."
    (cl-letf (((symbol-function #'message)
               (lambda (fmt &rest msg-args)
		 (user/message-after-startup
                  (apply #'format-message fmt msg-args)))))
      (apply orig-fun args)))
  :functions user/theme-functions
  :init
  (modus-themes-include-derivatives-mode 1)
  
  :custom
  (modus-themes-mixed-fonts t)
  (modus-themes-italic-constructs t)

  :config
  ;; This keymap is bound in a custom transient defined in 15-user-functions.el
  (defvar-keymap user/theme-functions
    :prefix t
    :doc "Functions to change the theme."
    "s" #'modus-themes-select-dark
    "r" #'modus-themes-load-random-dark
    "n" #'modus-themes-rotate)

  (user/delay-messages-around #'modus-themes-load-random 'dark)
  (add-hook 'server-after-make-frame-hook
	    #'(lambda ()
		(user/function-after-emacsclient-frame
		 #'modus-themes-load-random 'dark))))


;; =======  ICONS  =======
;; `nerd-icons' (icons)
;; `tab-line-nerd-icons' (nerd-icons in tab-line)
;; `nerd-icons-corfu' (nerd-icons in corfu)
;; =======================
(use-package nerd-icons
  :demand t
  :functions nerd-icons-install-fonts
  :config
  (when (and (not (member "Symbols Nerd Font Mono" (font-family-list)))
	     (window-system))
    (nerd-icons-install-fonts t)))

(use-package tab-line-nerd-icons
  :after nerd-icons
  :functions tab-line-nerd-icons-global-mode
  :config
  (tab-line-nerd-icons-global-mode 1))

(use-package nerd-icons-corfu
  :after nerd-icons
  :preface (defvar corfu-margin-formatters)
  :config
  (add-to-list 'corfu-margin-formatters 'nerd-icons-corfu-formatter))


;; =======  MODELINE  =======
;; `minons' (declutter modeline w/ menu for minor-modes)
;; ==========================
(use-package minions
  :demand t
  :functions minions-mode
  :config
  (minions-mode 1))


;; =======  VISUAL LINE  =======
;; `editorconfig' (support .editorconfig)
;; `visual-fill-column' (fill-column for visual-line-mode)
;; =============================
(use-package editorconfig
  :defer t
  :preface
  (defun user/function-for-editorconfig-hook ()
    "Use this as the function to add to *-mode-hook for editorconfig."
    (editorconfig-mode 1))
  :hook ((prog-mode text-mode conf-mode) . user/function-for-editorconfig-hook))

(use-package visual-fill-column
  :defer t
  :hook
  ((visual-line-mode               . visual-fill-column-for-vline)
   ((prog-mode text-mode conf-mode) . visual-line-mode)))

(use-package folding-mode
  :ensure nil
  :defer t
  :bind ("C-|" . folding-mode))


;; =======  WHICH-KEY  =======
;; `which-key' (needs to load before many other functions)
;; ===========================
(use-package which-key
  :demand t
  :config
  (which-key-mode 1))


(provide '03-visual-settings)
;;; 03-visual-settings.el ends here
