;;; 03-visual-settings.el --- Core UI configuration -*- lexical-binding: t; -*-

;;; Packages included:
;; minions, nerd-icons, nerd-icons-corfu, tab-line-nerd-icons, which-key

;;; Commentary:
;; Core UI elements that provide visual feedback and interaction.

;;; Code:
;; =======  HELPER FUNCTIONS  =======
(require 'cl-lib)
(declare-function user/function-after-emacsclient-frame "01-bootstrap-core.el")

;; Ensure theme message prints after startup
(defvar user/ef-themes-startup-messages nil)

(defun user/flush-startup-messages ()
  "Print messages held in `user/ef-themes-startup-messages'.
Messages are printed in the order in which they were received"
  (dolist (msg (nreverse user/ef-themes-startup-messages))
    (message "%s" msg))
  (setq user/ef-themes-startup-messages nil))

(defun user/message-after-startup (msg)
  "Wait until after init to print MSG.
If Emacs has already started, print MSG right away."
  (if after-init-time
      (message "%s" msg)
    (push msg user/ef-themes-startup-messages)
    (add-hook 'emacs-startup-hook #'user/flush-startup-messages)))

(defun user/delay-messages-around (orig-fun &rest args)
  "Delay the messages generated by ORIG-FUN until after startup.
Designed to be used with `advice-add', you can pass ARGS to the ORIG-FN
as well."
  (cl-letf (((symbol-function #'message)
             (lambda (fmt &rest msg-args)
	       (user/message-after-startup
                (apply #'format-message fmt msg-args)))))
    (apply orig-fun args)))


;; =======  INIT  =======
(add-to-list 'default-frame-alist '(fullscreen . maximized))
(set-face-attribute 'default nil :height 131)

(let* ((font (face-attribute 'default :family))
       (alist-entry (concat font "-13")))
  (add-to-list 'default-frame-alist `(font . ,alist-entry)))

;; =======  THEMES  =======
;; `modus-themes' (Collection of readable Emacs' themes)
;; `ef-themes' (Additional & enhanced Emacs' themes)
;; ================
(use-package modus-themes
  :functions
  modus-themes-include-derivatives-mode modus-themes-load-random-dark
  modus-themes-select-dark modus-themes-load-random modus-themes-rotate
  :demand t)

(use-package ef-themes
  :functions user/theme-functions
  :init
  (modus-themes-include-derivatives-mode 1)
  
  :config
  (setq
   modus-themes-mixed-fonts t
   modus-themes-italic-constructs t)

  ;; This keymap is bound in the custom transient defined in
  ;; 15-user-functions.el
  (defvar-keymap user/theme-functions
    :prefix t
    :doc "Keymap of functions affecting the theme."
    "s" #'modus-themes-select-dark
    "r" #'modus-themes-load-random-dark
    "n" #'modus-themes-rotate)

  (user/delay-messages-around #'modus-themes-load-random 'dark)
  (add-hook 'server-after-make-frame-hook
	    #'(lambda ()
		(user/function-after-emacsclient-frame
		 #'modus-themes-load-random 'dark))))


;; =======  ICONS  =======
;; `nerd-icons' (icons)
;; `tab-line-nerd-icons' (nerd-icons in tab-line)
;; `nerd-icons-corfu' (nerd-icons in corfu)
;; =======================
(use-package nerd-icons
  :functions nerd-icons-install-fonts
  :config
  (unless (member "Symbols Nerd Font Mono" (font-family-list))
    (when (window-system)
      (nerd-icons-install-fonts t))))

(use-package tab-line-nerd-icons
  :functions tab-line-nerd-icons-global-mode
  :config
  (tab-line-nerd-icons-global-mode 1))

(defvar corfu-margin-formatters)
(use-package nerd-icons-corfu
  :config
  (add-to-list 'corfu-margin-formatters 'nerd-icons-corfu-formatter))

(use-package minions
  :functions minions-mode
  :config
  (minions-mode 1)
  (add-to-list 'minions-prominent-modes 'flycheck-mode)
  (add-to-list 'minions-prominent-modes 'lsp-mode)
  (add-to-list 'minions-prominent-modes 'persp-mode))

;; Which-key needs to load before a lot of other editor functions,
;; which is why it's invoked here.
(use-package which-key
  :ensure (:wait t)
  :config
  (which-key-mode 1))

(use-package folding-mode
  :ensure nil
  :bind ("C-|" . folding-mode))


(provide '03-visual-settings)
;;; 03-visual-settings.el ends here
